/**
 * recalculate_monthly_reports.js
 * ───────────────────────────────────────────────────────────────────────────
 * آمن تماماً — يعيد حساب التقارير الشهرية المحفوظة باستخدام المنطق الجديد
 * الصحيح. لا يلمس الـ Orders أو Transactions أو Products.
 *
 * الاستخدام (من مجلد backend):
 *   node recalculate_monthly_reports.js           ← يحسب ويحدِّث كل التقارير
 *   node recalculate_monthly_reports.js --dry-run  ← يعرض الفرق بدون أي تعديل
 *
 * ───────────────────────────────────────────────────────────────────────────
 */

const dotenv = require('dotenv');
dotenv.config();

const mongoose = require('mongoose');
const connectDB = require('./config/db');
const MonthlyReport = require('./models/MonthlyReport');
const { calculateMonthlyData } = require('./services/monthlyReportService');

// ── Helpers ─────────────────────────────────────────────────────────────────

const fmt = (n) => (n ?? 0).toLocaleString('en-US', { maximumFractionDigits: 2 });
const diff = (oldVal, newVal) => {
  const d = (newVal ?? 0) - (oldVal ?? 0);
  if (d === 0) return '  (no change)';
  return d > 0 ? `  +${fmt(d)} ↑` : `  ${fmt(d)} ↓`;
};

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const isDryRun = process.argv.includes('--dry-run');

  if (isDryRun) {
    console.log('\n🔍 DRY RUN MODE — لن يتم حفظ أي تغييرات\n');
  } else {
    console.log('\n🔄 LIVE MODE — سيتم تحديث التقارير المحفوظة\n');
  }

  await connectDB();

  // اجلب كل التقارير الموجودة مرتبة من الأقدم للأحدث
  const existingReports = await MonthlyReport.find({})
    .sort({ year: 1, month: 1 })
    .lean();

  if (existingReports.length === 0) {
    console.log('⚠️  لا توجد تقارير شهرية محفوظة في قاعدة البيانات.');
    await mongoose.disconnect();
    return;
  }

  console.log(`📋 عدد التقارير الموجودة: ${existingReports.length}\n`);
  console.log('━'.repeat(70));

  let updatedCount = 0;
  let skippedCount = 0;
  let errorCount = 0;

  for (const oldReport of existingReports) {
    const { year, month, yearMonth, monthName } = oldReport;
    process.stdout.write(`\n📅 ${monthName} (${yearMonth})...\n`);

    try {
      // أعد حساب البيانات بالمنطق الجديد الصحيح
      const newData = await calculateMonthlyData(year, month);

      // اعرض الفرق في الأرقام الرئيسية
      const fields = [
        ['totalSales',        'إجمالي المبيعات  '],
        ['netProfit',         'صافي الربح       '],
        ['operatingExpenses', 'مصاريف التشغيل   '],
        ['supplierPurchases', 'مشتريات الموردين '],
        ['totalExpenses',     'إجمالي المصاريف  '],
        ['netCashFlow',       'صافي حركة الخزنة '],
        ['cashRevenue',       'إيراد كاش        '],
        ['instapayRevenue',   'إيراد إنستاباي   '],
      ];

      let hasChanges = false;
      for (const [key, label] of fields) {
        const oldVal = oldReport[key] ?? 0;
        const newVal = newData[key] ?? 0;
        if (Math.abs(oldVal - newVal) > 0.001) {
          hasChanges = true;
          console.log(`   ${label}: ${fmt(oldVal)} → ${fmt(newVal)} ج.م${diff(oldVal, newVal)}`);
        }
      }

      if (!hasChanges) {
        console.log('   ✅ لا فرق — البيانات كانت صح أصلاً');
        skippedCount++;
        continue;
      }

      if (!isDryRun) {
        // احفظ التقرير المحدَّث (upsert آمن — لا يحذف شيئاً)
        const now = new Date();
        const isPastMonth =
          year < now.getFullYear() ||
          (year === now.getFullYear() && month < now.getMonth() + 1);

        await MonthlyReport.findOneAndUpdate(
          { yearMonth },
          {
            ...newData,
            isClosed: isPastMonth,
            closedAt: isPastMonth ? now : undefined,
            autoGenerated: true
          },
          { upsert: true, new: true, setDefaultsOnInsert: true }
        );
        console.log('   💾 تم الحفظ بنجاح');
        updatedCount++;
      } else {
        console.log('   ⏭  (dry-run: لم يُحفَظ)');
        updatedCount++;
      }
    } catch (err) {
      console.error(`   ❌ خطأ أثناء معالجة ${yearMonth}: ${err.message}`);
      errorCount++;
    }
  }

  // ── ملخص نهائي ───────────────────────────────────────────────────────────
  console.log('\n' + '━'.repeat(70));
  console.log('\n📊 ملخص العملية:');
  console.log(`   ✅ تقارير ${isDryRun ? 'ستتغير' : 'تم تحديثها'}: ${updatedCount}`);
  console.log(`   ⏩ تقارير بدون تغيير:   ${skippedCount}`);
  if (errorCount > 0) {
    console.log(`   ❌ تقارير فيها خطأ:     ${errorCount}`);
  }
  console.log('');

  if (isDryRun && updatedCount > 0) {
    console.log('💡 لتطبيق التغييرات فعلياً شغَّل:\n');
    console.log('   node recalculate_monthly_reports.js\n');
  }

  await mongoose.disconnect();
  console.log('🔌 تم قطع الاتصال بقاعدة البيانات.\n');
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
