/**
 * fix_monthly_reports.js — Phase 2: Regenerate all past monthly reports with corrected logic.
 *
 * Run: node backend/scripts/fix_monthly_reports.js           (dry-run, shows what will change)
 *      node backend/scripts/fix_monthly_reports.js --apply   (regenerates and saves reports)
 */
require("dotenv").config({ path: require("path").join(__dirname, "../.env") });
const mongoose = require("mongoose");
const MonthlyReport = require("../models/MonthlyReport");
const { generateAndSaveReport } = require("../services/monthlyReportService");

const applyChanges = process.argv.includes("--apply");

async function main() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log(`Connected. Mode: ${applyChanges ? "APPLY" : "DRY-RUN"}`);

  const existingReports = await MonthlyReport.find({}).sort({ yearMonth: 1 });
  console.log(`Found ${existingReports.length} reports to regenerate.`);

  for (const report of existingReports) {
    const { year, month, yearMonth, totalSales, netProfit, netCashFlow } = report;
    console.log(`\nProcessing ${yearMonth} — old: sales=${totalSales}, profit=${netProfit}, cashflow=${netCashFlow}`);

    if (applyChanges) {
      const newReport = await generateAndSaveReport(year, month, report.autoGenerated ?? true);
      console.log(`  => new: sales=${newReport.totalSales}, profit=${newReport.netProfit}, cashflow=${newReport.netCashFlow}`);
    }
  }

  if (!applyChanges) {
    console.log("\n[DRY-RUN] No changes saved. Run with --apply to regenerate.");
  } else {
    console.log(`\nDone. ${existingReports.length} reports regenerated.`);
  }
  await mongoose.disconnect();
}

main().catch(err => { console.error(err); process.exit(1); });
