const mongoose = require('mongoose');

const DailySummarySchema = new mongoose.Schema({
  day: { type: Number, required: true },
  date: { type: String, required: true },
  revenue: { type: Number, default: 0 },
  profit: { type: Number, default: 0 },
  count: { type: Number, default: 0 },
  cashRevenue: { type: Number, default: 0 },
  instapayRevenue: { type: Number, default: 0 },
  expenses: { type: Number, default: 0 },
  operatingExpenses: { type: Number, default: 0 },
  supplierPurchases: { type: Number, default: 0 }
}, { _id: false });

const MonthlyReportSchema = new mongoose.Schema({
  year: { type: Number, required: true },
  month: { type: Number, required: true }, // 1-12
  yearMonth: { type: String, required: true, unique: true }, // e.g. "2026-07"
  monthName: { type: String, required: true }, // e.g. "يوليو 2026"
  totalSales: { type: Number, default: 0 },
  netProfit: { type: Number, default: 0 },
  totalExpenses: { type: Number, default: 0 },
  operatingExpenses: { type: Number, default: 0 },
  supplierPurchases: { type: Number, default: 0 },
  netCashFlow: { type: Number, default: 0 },
  totalDiscounts: { type: Number, default: 0 },
  totalOrders: { type: Number, default: 0 },
  cashRevenue: { type: Number, default: 0 },
  instapayRevenue: { type: Number, default: 0 },
  dailyData: [DailySummarySchema],
  expenseBreakdown: [{
    category: String,
    amount: Number
  }],
  categoryBreakdown: [{
    category: String,
    amount: Number
  }],
  bestSellers: [{
    name: String,
    qty: Number
  }],
  employeePerformance: [{
    name: String,
    amount: Number,
    profit: Number,
    orderCount: Number,
    itemsSold: Number
  }],
  isClosed: { type: Boolean, default: false },
  closedAt: { type: Date },
  autoGenerated: { type: Boolean, default: true },
  auditDetails: { type: Object }
}, { timestamps: true });

MonthlyReportSchema.index({ year: 1, month: 1 }, { unique: true });

module.exports = mongoose.model('MonthlyReport', MonthlyReportSchema);
